Project
std::string Project::_filename
Referenced by Open, Project.
bool Project::_isOpen
Referenced by Close, GetBuild, GetEntities, GetFiles, GetLanguage, GetMetrics, GetName, Open, Project.
Project::Project(std::string filename)
References _filename, _isOpen.
Project::~Project()
bool Project::Open()
References _filename, _isOpen.
Referenced by main.
void Project::Close()
References _isOpen.
Referenced by main.
Language Project::GetLanguage() const
References _isOpen, Util::GetLanguage.
std::string Project::GetName() const
References _isOpen.
std::string Project::GetBuild() const
References _isOpen.
std::list< Entity * > Project::GetFiles() const
References _isOpen.
std::list< Entity * > Project::GetEntities() const
References _isOpen.
Referenced by ListEntities.
std::list< Metric * > Project::GetMetrics() const
References _isOpen.
Referenced by ListProjectMetrics.