Reference
int Reference::_sourceEntityId
Referenced by GetSourceEntityId, Reference.
std::string Reference::_sourceEntityName
Referenced by GetSourceEntityName, Reference.
std::string Reference::_sourceEntityKindName
Referenced by GetSourceEntityKindName, Reference.
int Reference::_targetEntityId
Referenced by GetTargetEntityId, Reference.
std::string Reference::_targetEntityName
Referenced by GetTargetEntityName, Reference.
std::string Reference::_targetEntityKindName
Referenced by GetTargetEntityKindName, Reference.
ReferenceKind Reference::_kind
Referenced by GetKind, Reference.
std::string Reference::_file
Referenced by GetFile, Reference.
int Reference::_line
Referenced by GetLine, Reference.
int Reference::_column
Referenced by GetColumn, Reference.
std::string Reference::_kindText
Referenced by GetKindText, Reference.
Reference::Reference(UdbEntity sourceEntity, UdbReference udbReference, UdbLanguage udbLanguage)
References _column, _file, _kind, _kindText, _line, _sourceEntityId, _sourceEntityKindName, _sourceEntityName, _targetEntityId, _targetEntityKindName, _targetEntityName, OtherReferenceKind.
Reference::~Reference()
int Reference::GetSourceEntityId() const
References _sourceEntityId.
std::string Reference::GetSourceEntityName() const
References _sourceEntityName.
std::string Reference::GetSourceEntityKindName() const
References _sourceEntityKindName.
int Reference::GetTargetEntityId() const
References _targetEntityId.
Referenced by ListEntities.
std::string Reference::GetTargetEntityName() const
References _targetEntityName.
Referenced by ListEntities.
std::string Reference::GetTargetEntityKindName() const
References _targetEntityKindName.
Referenced by ListEntities.
ReferenceKind Reference::GetKind() const
References _kind.
std::string Reference::GetFile() const
References _file.
int Reference::GetLine() const
References _line.
int Reference::GetColumn() const
References _column.
std::string Reference::GetKindText() const
References _kindText.
Referenced by ListEntities.