ReferenceKindsParser
ReferenceKind ReferenceKindsParser::__referencKind
ReferenceKindsParser::ReferenceKindsParser(std::string kind, UdbLanguage udbLanguage)
References ParseCppKinds, ParseCSharpKinds, ParseJavaKinds.
ReferenceKindsParser::~ReferenceKindsParser()
void ReferenceKindsParser::ParseCppKinds(std::string kind)
References stringComparer::ContainsText.
Referenced by ReferenceKindsParser.
void ReferenceKindsParser::ParseCSharpKinds(std::string kind)
References stringComparer::ContainsText.
Referenced by ReferenceKindsParser.
void ReferenceKindsParser::ParseJavaKinds(std::string kind)
References stringComparer::ContainsText.
Referenced by ReferenceKindsParser.