Entity
int Entity::_id
Referenced by Entity, GetId.
std::string Entity::_namespace
Referenced by Entity, GetNamespace.
std::string Entity::_name
Referenced by Entity, GetName.
std::string Entity::_type
Referenced by Entity, GetType.
Scope Entity::_scope
Referenced by Entity, GetScope.
EntityKind Entity::_kind
Referenced by Entity, GetKind.
Language Entity::_language
Referenced by Entity, GetLanguage.
std::list<Reference*> Entity::_references
Referenced by Entity, GetReferences.
std::list<Metric*> Entity::_metrics
Referenced by Entity, GetMetrics.
std::string Entity::_comment
Referenced by Entity, GetComment.
std::string Entity::_kindText
Referenced by Entity, GetKindText.
Entity::Entity(UdbEntity udbEntity, UdbLanguage udbLanguage)
References _comment, _id, _kind, _kindText, _language, _metrics, _name, _namespace, _references, _scope, _type, Util::GetLanguage, OtherEntityKind, OtherScope.
Entity::~Entity()
int Entity::GetId() const
References _id.
Referenced by ListEntities.
std::string Entity::GetNamespace() const
References _namespace.
std::string Entity::GetName() const
References _name.
Referenced by ListEntities.
std::string Entity::GetType() const
References _type.
Referenced by ListEntities.
Scope Entity::GetScope() const
References _scope.
EntityKind Entity::GetKind() const
References _kind.
Language Entity::GetLanguage() const
References _language.
std::list< Reference * > Entity::GetReferences() const
References _references.
Referenced by ListEntities.
std::list< Metric * > Entity::GetMetrics() const
References _metrics.
std::string Entity::GetComment() const
References _comment.
std::string Entity::GetKindText() const
References _kindText.
Referenced by ListEntities.