stringComparer
std::string stringComparer::_text
Referenced by ContainsText, stringComparer.
stringComparer::stringComparer(std::string text)
References _text.
stringComparer::~stringComparer()
bool stringComparer::ContainsText(std::string substring) const
References _text.
Referenced by EntityKindParser::ParseCppKinds, ReferenceKindsParser::ParseCppKinds, EntityKindParser::ParseCSharpKinds, ReferenceKindsParser::ParseCSharpKinds, EntityKindParser::ParseJavaKinds, ReferenceKindsParser::ParseJavaKinds.